### ISSUE TITLE
Code Smell

### ISSUE THREAD

**Issue by Iostream3100** [Iostream3100/Studio-Web#83]
Demo test Page:

1. Duplicated code: It would be better to add these repeated code to the `beforeEach` scope.
![image](https://user-images.githubusercontent.com/39519369/203625447-0d6283a4-f91a-4f10-9789-af8c80affd6e.png)
2. Long Method: arr variable is too long, should use a for loop to generate the characters. 
![image](https://user-images.githubusercontent.com/39519369/203625559-49e2e56c-a0f6-4b07-8822-e0f93b57d706.png)
3. Mysterious Name: `index`, `arr` and `returnStr` do not have a clear meaning.
![image](https://user-images.githubusercontent.com/39519369/203625583-634a121c-f78b-41fe-84ff-982c4e4c2d91.png)

**Comment by guanxiaotongyz** [comment]
Duplicated code is indeed appear, it should be revised. great idea to  add these repeated code to the outer scope.
Also, Long Method is not only appear test part , Also In the milestone 3, 
Original -> we just "convert to b64input[1]"  part  to download function,
After revise -> we create new function called `updateTextXML() ` and recall it in download function.

```
//pass all sentences to b64Inputs[1]
  updateTextXML(): void {
    // @ts-ignore
    const readalongRoot: any = document.querySelector("read-along").shadowRoot;
    if (readalongRoot == null) {
      return;
    }
    const translation = readalongRoot.querySelectorAll(".translation");
    var textXML = this.b64Service.b64_to_utf8(
      this.b64Inputs[1].substring(this.b64Inputs[1].indexOf(",") + 1)
    );

    const parser = new DOMParser();
    const doc = parser.parseFromString(textXML, "application/xml");
    // if translation class exist, delete it
    if (doc.querySelector(".translation") != null) {
      doc.querySelectorAll(".translation").forEach((node) => {
        node.remove();
      });
    }
    const ss = doc.querySelectorAll("s");
    let count = 0;
    ss.forEach((tag_s) => {
      tag_s.insertAdjacentHTML(
        "afterend",
        `<span class="translation" contenteditable="true">${translation[count].innerHTML}</span>`
      );
      count++;
    });

    const serializer = new XMLSerializer();
    const xmlStr = serializer.serializeToString(doc);
    this.b64Inputs[1] =
      this.b64Inputs[1].slice(0, this.b64Inputs[1].indexOf(",") + 1) +
      this.b64Service.utf8_to_b64(xmlStr);
  }

  download() {
    // recall updatetextXML()
    this.updateTextXML();

```

**Comment by crystaljesica** [comment]
- duplicate code
   in the test of milestone1, there are some duplicate code.
   for this one, it's better to write a new function to generate the string for test.
![image](https://user-images.githubusercontent.com/90473229/203729330-35a1e864-847f-4013-9941-21ebd2c3ef9a.png)

- Mysterious Name
  For our project's repo, for example we have functions named 'picked', the name of the function can be confusing to other 
  people. 
![image](https://user-images.githubusercontent.com/90473229/203745890-0b6cd6e4-8010-4440-a0c2-b55d28ce13b0.png)

  Refactor: So we would better give these functions a more detailed name to explain or write a documentation above each 
  function to explain what these functions are doing. 

- Long method
 For our repo, the download function is too long. For this function, we include changing the innerhtml, converting the base64 input and also the append node to the page element. In my opinion, it's usually a very good idea to split large functions into smaller ones. It's not a problem if they are well designed and it's easy to understand what is going on. But the larger the function, the harder it becomes to do so. Keeping functions simple will allow you to track problems easier later on. As we go through the implementation of the function, we may also add more lines of additional innerhtml for the sentence elements which would make the download function longer.
![image](https://user-images.githubusercontent.com/90473229/203746562-9798942c-a2f0-4f12-b7fb-339c5278a80f.png)

refactor: separate the download function or write a function implement the add innerhtml, then call that function inside the download function
benefits:same to large class, if we separate into smaller codebase, it would be clean and sustainable in the future. 

- Data clump
  It happens in our repo that a group of variables(base64inputs) are passed around together in various parts of the program. Because we would always need to convert the string/ images into base 64 input format and our download function also depends on this.
refactor: it would be more appropriate for us to formally group the different variables together into a single object, and pass around only the new object instead
benefits: we don’t need to write the process of converting the base64 input again and again. Save time, increase efficiency.

![image](https://user-images.githubusercontent.com/90473229/203747258-3d30c191-f8c0-45f1-8fe9-9cf1d72efb36.png)

- Variable mutations

mutations that vary widely enough that refactoring the code becomes increasingly difficult, due to the actual value's status as unpredictable and hard to reason about.For some of our code, our variable’s type is any which will make it harder to debug and confused of the status of the variable.
![image](https://user-images.githubusercontent.com/90473229/203747794-31c713e6-a42b-4709-b81a-e8d3e176b028.png)
![image](https://user-images.githubusercontent.com/90473229/203747831-f421081e-ae02-4c8e-9bcb-357d7f3300d5.png)

Refactor: change the type of variable, let it more specific
Benefits: easy for debugging, easy to track the process

- large class
For our own repo, there is a class named 'DemoComponent' which contains lots of functions. 
refactor: So we may pay attention to this class and see whether we could separate it into several different classes. Each class can contain less function like image class or input class.
benefits: more flexible and maintainable for future modifications.Easier to understand the logic of each function.

**Comment by yoxchen95** [comment]
1.Mysterious Name: functions, modules, variables or classes that are named in a way that does not communicate what they do or how to use them
In our repo, I think there is some function without friendly instructions.Although part of them is easy to understand without comments, parts of them may be hard to know how to handle with parameters. As a result , it is not an easy thing to understand the repo for new learner.I think it is the most important thing we have to follow up involving the code smell.
<img width="561" alt="image" src="https://user-images.githubusercontent.com/98132024/203875167-fae3237b-2fd1-41d0-9b0d-7cd4e5d1ad7c.png">
Before refactoring this function is called download, from which we can’t tell what the function can really do. After refactoring, we know the function is called for downloading the web file with recording.

2.Duplicated code: identical or very similar code that exists in more than one location.

 In our repo, many functions have similar need to deal with the encoding content. Hence, it is easy to write the similar code especially if we have four teammates. If we discuss further before coding, it may ease this situation. As a result, we have to follow up our own encoding or decoding.

<img width="701" alt="image" src="https://user-images.githubusercontent.com/98132024/203875342-75847d68-1b54-423b-baff-e8f45d539c74.png">
For example, we all have the similiar function to get the element with querySelector, but at first we all use .image to get the default image. But when I deal with my part. I find that it may be a little mistake when I using delete button to delete the image. Hence ,it maybe cause other people's function doesn't work well. And we shoudle refactor it to querySelector(.page) instead. 

3.Shotgun surgery: a single change that needs to be applied to multiple classes at the same time.
It is basically the same situation I mentioned in 2 . The simple change may have to be rewritten in every similar parts to do that.

4.Lazy class/freeloader: a class that does too little.
There are some functions just for simple use. Hence, these functions are very short and just for one simple usage.

private appendToChunks = (event: any) => {
   this.chunks.push(event.data);
 };

This function is just simple pushing. It can be considered as a lazy class.
It can be added into other functions.

5.Long method: a method, function, or procedure that has grown too large.
<img width="751" alt="image" src="https://user-images.githubusercontent.com/98132024/203876511-02f7fe1f-642f-4c45-9176-a73e64ccf59d.png">

As for our repo, all the download functions can be considered long method. Cause we have to add encoding functions and deal with the certain code to get the index of string file and make them visible to the html that be downloaded. Hence, it turns out to be more and more large.
The possible way to fix that is to seperate the whole function into some little function like dealing with the string and call this funcion in download funcion. It is a relatively easy way to do that.

6.Excessively short identifiers: the name of a variable should reflect its function unless the function is obvious.
<img width="486" alt="image" src="https://user-images.githubusercontent.com/98132024/203878780-655b3893-a867-4dc8-89d5-28d8828ddb5e.png">
This function shoulde be refactored as choose_images function. In case the stakeholders can't easily understand the function.
